-- seeds for types table
INSERT INTO
  types (name)
VALUES
  ('donor'),
  ('receiver_organization'),
  ('receiver_individual');

-- seeds for categories table
INSERT INTO
  categories (name)
VALUES
  ('Health'),
  ('Food Banks'),
  ('Immigration & Refugees'),
  ('Education'),
  ('Animals'),
  ('Kids'),
  ('Women'),
  ('Others');

-- seeds for users table
INSERT INTO
  users (
    username,
    email,
    password,
    type_id,
    avatar,
    category_id
  )
VALUES
  (
    'helloWorld',
    'hello@world.com',
    'helloworld',
    1,
    'https://avatars.dicebear.com/v2/female/f3f1f083c911e25d5350659901780358.svg',
    2
  ),
  (
    'World Heath Organization',
    'who@example.com',
    'password',
    2,
    'https://gravatar.com/avatar/f3f1f083c911e25d5350659901780358?s=400&d=robohash&r=x',
    null
  ),
  (
    'share food bank',
    'sfb@example.com',
    'password',
    2,
    'https://gravatar.com/avatar/f3f1f083c911e25d5350659901780358?s=400&d=retro&r=x',
    null
  ),
  (
    'JoeD',
    'joe@example.com',
    'password',
    1,
    'https://gravatar.com/avatar/f3f1f083c911e25d5350659901780358?s=400&d=monsterid&r=x',
    null
  ),
  (
    'MrDave',
    'dave@example.com',
    'password',
    3,
    'https://gravatar.com/avatar/f3f1f083c911e25d5350659901780358?s=400&d=retro&r=x',
    1
  ),
  (
    'fpowelee0',
    'lhatcliffe0@clickbank.net',
    'K4DCtnA',
    1,
    'https://robohash.org/reprehenderitadea.jpg?size=50x50&set=set1',
    8
  ),
  (
    'thasard1',
    'ckopman1@upenn.edu',
    'U9lhtWIALu',
    2,
    'https://robohash.org/autemiderror.png?size=50x50&set=set1',
    8
  ),
  (
    'glesper2',
    'lsleaford2@cloudflare.com',
    'N8nFcpuzszH',
    1,
    'https://robohash.org/sintiuremolestias.bmp?size=50x50&set=set1',
    7
  ),
  (
    'lvasyuchov3',
    'rchapiro3@archive.org',
    'CGmHiW7KG9',
    2,
    'https://robohash.org/deseruntestab.bmp?size=50x50&set=set1',
    7
  ),
  (
    'fhatherleigh4',
    'lweitzel4@prlog.org',
    'mF0S72ds0',
    2,
    'https://robohash.org/quipariaturnulla.jpg?size=50x50&set=set1',
    1
  ),
  (
    'wmayhow5',
    'ecracknall5@webnode.com',
    'PqkXuHLX',
    2,
    'https://robohash.org/nihilaccusantiumtotam.png?size=50x50&set=set1',
    1
  ),
  (
    'haddeycott6',
    'taronowitz6@businessweek.com',
    'clzNWM2arnQ9',
    2,
    'https://robohash.org/recusandaeexercitationemqui.bmp?size=50x50&set=set1',
    1
  ),
  (
    'nhumbee7',
    'wslany7@google.com',
    'OdS22xftZ',
    2,
    'https://robohash.org/utrepellendusmolestiae.jpg?size=50x50&set=set1',
    3
  ),
  (
    'rsilcocks8',
    'nmouan8@opera.com',
    'QPBOJAqJMM55',
    2,
    'https://robohash.org/rerumconsequunturnon.bmp?size=50x50&set=set1',
    1
  ),
  (
    'lblaiklock9',
    'kleitche9@dropbox.com',
    'aEXJXdf7vok',
    1,
    'https://robohash.org/autemquisin.png?size=50x50&set=set1',
    7
  ),
  (
    'eyounga',
    'lballingera@java.com',
    '3x0UStsdMDuW',
    3,
    'https://robohash.org/atquiahic.bmp?size=50x50&set=set1',
    6
  ),
  (
    'tmacclureb',
    'lwinspurrb@sourceforge.net',
    '0XteuM',
    1,
    'https://robohash.org/nisiistemaxime.png?size=50x50&set=set1',
    8
  ),
  (
    'wwychec',
    'draccioc@discuz.net',
    'Tavngty3Fhs',
    1,
    'https://robohash.org/culpamagnidignissimos.jpg?size=50x50&set=set1',
    2
  ),
  (
    'dcuddd',
    'dtumed@bluehost.com',
    'xE1aTrb1NAC',
    2,
    'https://robohash.org/commodiquiculpa.bmp?size=50x50&set=set1',
    5
  ),
  (
    'vwheatlande',
    'imcwhinniee@usgs.gov',
    '4i3SpTX',
    1,
    'https://robohash.org/veritatisrerumquia.png?size=50x50&set=set1',
    2
  ),
  (
    'amogganf',
    'agureryf@storify.com',
    'dknmGryY',
    3,
    'https://robohash.org/repudiandaeetsint.png?size=50x50&set=set1',
    2
  ),
  (
    'jrapperg',
    'nkeniong@pinterest.com',
    'ztQX6KqU',
    3,
    'https://robohash.org/voluptatemrepellendusut.jpg?size=50x50&set=set1',
    5
  ),
  (
    'cstonbridgeh',
    'abintonh@toplist.cz',
    'd6h22I',
    3,
    'https://robohash.org/illoveniamarchitecto.bmp?size=50x50&set=set1',
    4
  ),
  (
    'lchazottei',
    'aglastonburyi@topsy.com',
    '4Od0T15ohPq',
    3,
    'https://robohash.org/velitomnisofficiis.png?size=50x50&set=set1',
    3
  ),
  (
    'aginnj',
    'ccardoj@hatena.ne.jp',
    'ZTOZ0npA0',
    2,
    'https://robohash.org/odiofacerecommodi.jpg?size=50x50&set=set1',
    3
  ),
  (
    'frillattk',
    'jbrusterk@sogou.com',
    'JYvnvosy',
    2,
    'https://robohash.org/enimquibusdamdicta.png?size=50x50&set=set1',
    4
  ),
  (
    'rporteousl',
    'gbeasleyl@umich.edu',
    'opZkataq2ycE',
    3,
    'https://robohash.org/magniidquia.png?size=50x50&set=set1',
    5
  ),
  (
    'szukermanm',
    'disaaksohnm@altervista.org',
    'FodboE',
    3,
    'https://robohash.org/quiaautiusto.jpg?size=50x50&set=set1',
    1
  ),
  (
    'rbremondn',
    'mtwinbournen@lulu.com',
    'I8TYvP16dPoD',
    3,
    'https://robohash.org/verovoluptatemrem.jpg?size=50x50&set=set1',
    4
  ),
  (
    'nbreedero',
    'ecurteiso@blog.com',
    'mv0pyCoc3',
    1,
    'https://robohash.org/etvoluptatesrepellendus.png?size=50x50&set=set1',
    3
  ),
  (
    'dmaddinp',
    'cantonazzip@mozilla.org',
    '4NRdasYn',
    2,
    'https://robohash.org/culpadoloremqui.jpg?size=50x50&set=set1',
    3
  ),
  (
    'ryushankinq',
    'jbraycottonq@feedburner.com',
    '5Vso8fPYiGj',
    2,
    'https://robohash.org/cupiditateautemmolestias.png?size=50x50&set=set1',
    3
  ),
  (
    'asouthernsr',
    'wrudledger@skyrock.com',
    'NHHmBJlDF',
    2,
    'https://robohash.org/autemvoluptasmagni.jpg?size=50x50&set=set1',
    6
  ),
  (
    'mpamplins',
    'dmasdings@xinhuanet.com',
    'FobQLNLvqyGy',
    1,
    'https://robohash.org/estquidemvoluptatem.png?size=50x50&set=set1',
    4
  ),
  (
    'mgallimoret',
    'alovittt@exblog.jp',
    '4vN8f0I5',
    2,
    'https://robohash.org/facerequidemnon.png?size=50x50&set=set1',
    2
  ),
  (
    'dgappu',
    'kmitkcovu@pbs.org',
    'g5ddAVbCTLWB',
    2,
    'https://robohash.org/harumlaborequo.jpg?size=50x50&set=set1',
    4
  ),
  (
    'jcarrolv',
    'ggoodwillv@google.co.uk',
    'cbsnHCq',
    1,
    'https://robohash.org/velaccusantiumodio.png?size=50x50&set=set1',
    3
  ),
  (
    'aabelovw',
    'pdavidaiw@yelp.com',
    '78FwvXxDc',
    3,
    'https://robohash.org/perferendisvelitharum.png?size=50x50&set=set1',
    2
  ),
  (
    'sdelmontix',
    'ebiddlecombex@pinterest.com',
    'yX7DSvx',
    2,
    'https://robohash.org/velitsuscipitqui.bmp?size=50x50&set=set1',
    8
  ),
  (
    'lkalkofeny',
    'tshakespearey@netvibes.com',
    'tkKcFl5',
    2,
    'https://robohash.org/eumtotamsunt.jpg?size=50x50&set=set1',
    8
  ),
  (
    'sdegenhardtz',
    'mbecketz@amazon.co.uk',
    'Yeqzxwl',
    2,
    'https://robohash.org/eaquefaciliscumque.png?size=50x50&set=set1',
    6
  ),
  (
    'aenrdigo10',
    'abilovsky10@vistaprint.com',
    'IHyOVhbJzj5',
    1,
    'https://robohash.org/consequaturnihildicta.jpg?size=50x50&set=set1',
    8
  ),
  (
    'jocassidy11',
    'abeloe11@storify.com',
    'OG6mXe',
    2,
    'https://robohash.org/velitsapientedolores.png?size=50x50&set=set1',
    2
  ),
  (
    'rgrundwater12',
    'ohassan12@sfgate.com',
    'asKwvH5C4Tt',
    3,
    'https://robohash.org/quocummolestias.bmp?size=50x50&set=set1',
    6
  ),
  (
    'rchamberlen13',
    'jbrockherst13@altervista.org',
    '5DcIuGM',
    3,
    'https://robohash.org/laborumnemocum.png?size=50x50&set=set1',
    7
  ),
  (
    'cbeswick14',
    'ahorick14@walmart.com',
    'yLBr2s',
    2,
    'https://robohash.org/fugiatquiaincidunt.png?size=50x50&set=set1',
    7
  ),
  (
    'averrier15',
    'glammerts15@xinhuanet.com',
    'd2fWY5QaI',
    3,
    'https://robohash.org/ipsumdoloremqueinventore.jpg?size=50x50&set=set1',
    6
  ),
  (
    'bpfaffel16',
    'hbedingfield16@amazon.co.uk',
    'yW8pHcqDyM',
    2,
    'https://robohash.org/enimcummagni.jpg?size=50x50&set=set1',
    3
  ),
  (
    'aenric17',
    'lsushams17@edublogs.org',
    'FXihKqZBk',
    2,
    'https://robohash.org/suscipitdictain.jpg?size=50x50&set=set1',
    2
  ),
  (
    'blorent18',
    'egossipin18@geocities.com',
    'MNRom5U1jCAh',
    2,
    'https://robohash.org/consequaturlaudantiumrecusandae.png?size=50x50&set=set1',
    8
  ),
  (
    'ulawdham19',
    'gdrains19@walmart.com',
    'nQ5AgmTG',
    2,
    'https://robohash.org/siteumqui.jpg?size=50x50&set=set1',
    5
  ),
  (
    'imirrlees1a',
    'ibalogh1a@imgur.com',
    'j861iiS9Ri',
    1,
    'https://robohash.org/remnesciuntrerum.png?size=50x50&set=set1',
    4
  ),
  (
    'ejosephsen1b',
    'mcuppleditch1b@woothemes.com',
    'qc6e6cS5fOR6',
    3,
    'https://robohash.org/illumexercitationemdebitis.bmp?size=50x50&set=set1',
    3
  ),
  (
    'elavies1c',
    'iknevett1c@plala.or.jp',
    'dMvsonB3f',
    2,
    'https://robohash.org/veliteumut.jpg?size=50x50&set=set1',
    1
  ),
  (
    'agallimore1d',
    'gloiterton1d@ebay.com',
    'I1VZ4w7MKr',
    2,
    'https://robohash.org/itaquesitquia.jpg?size=50x50&set=set1',
    4
  );

-- seeds for request volunteer table
INSERT INTO
  request_volunteer (
    volunteer_id,
    description,
    title,
    start_date,
    end_date,
    start_time,
    end_time,
    is_active,
    requestor_id
  )
VALUES
  (
    1,
    'Need some help in cleaning the lawn and planting it together, it is a big lawn',
    'Lawn work',
    '03-06-2020',
    '03-06-2020',
    '08:00:00',
    '11:00:00',
    TRUE,
    5
  ),
  (
    4,
    'Need some help to move in to a new home and it will be having some heavy lifting',
    'Moving help',
    '10-02-2020',
    '10-02-2020',
    '08:00:00',
    '15:00:00',
    TRUE,
    5
  ),
  (
    4,
    'Need a person to help in a food distribution week for the community of Burnaby and it will be for 4 days',
    'Food Bank help',
    '10-05-2020',
    '10-08-2020',
    '09:00:00',
    '14:00:00',
    TRUE,
    3
  ),
  (
    1,
    'We need help in community vaccination day, you will not vaccinate but will help in organizing the patients and other related chores',
    'Community Vaccine Day',
    '03-31-2021',
    '03-31-2021',
    '08:00:00',
    '09:00:00',
    TRUE,
    2
  );

-- seeds for items wishlist table
INSERT INTO
  items_wishlist (
    user_id,
    category_id,
    item_name,
    is_active,
    entry_date,
    donated_date,
    quantity
  )
VALUES
  (2, 5, 'Dog food', TRUE, '12-15-2020', null, 3),
  (2, 5, 'Puppy pads', TRUE, '12-15-2020', null, 10),
  (3, 2, 'Rice bags', TRUE, '01-20-2021', null, 3),
  (
    3,
    2,
    'Canned beans',
    TRUE,
    '01-25-2021',
    null,
    5
  ),
  (5, 6, 'Markers', TRUE, '03-02-2021', null, 10),
  (5, 6, 'Note pads', TRUE, '03-02-2021', null, 10),
  (5, 6, 'Scissors', TRUE, '05-02-2021', null, 2);

-- seeds for requested money table
INSERT INTO
  requested_money (user_id, is_active, requested_amount)
VALUES
  (2, TRUE, 1000),
  (3, TRUE, 500);

-- seeds for donated money table
INSERT INTO
  donated_money (
    user_id,
    donation_date,
    donated_amount,
    requested_money_id
  )
VALUES
  (1, '06-03-2020', 100, 1),
  (4, '06-20-2020', 250, 1),
  (1, '09-15-2020', 300, 2);